"""empty message

Revision ID: 5f5e37e37a55
Revises: f01fa4f04031
Create Date: 2021-05-28 17:19:16.671433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5e37e37a55'
down_revision = 'f01fa4f04031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_model', sa.Column('pickle_obj', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_model', 'pickle_obj')
    # ### end Alembic commands ###
