"""empty message

Revision ID: 223b0863f13e
Revises: ada9aad76ad8
Create Date: 2021-05-28 15:58:12.750499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223b0863f13e'
down_revision = 'ada9aad76ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_model', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_model', 'page')
    # ### end Alembic commands ###
