"""empty message

Revision ID: ada9aad76ad8
Revises: 38c464911733
Create Date: 2021-05-28 15:41:51.432230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada9aad76ad8'
down_revision = '38c464911733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_model', sa.Column('instance_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_model', 'instance_count')
    # ### end Alembic commands ###
